services:
  - type: web
    name: matchma
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
